[package]
name = "firment-tools"
version.workspace = true
edition.workspace = true

[dependencies]
firment-core = { path = "../firment-core" }
async-trait.workspace = true
globset.workspace = true
ignore.workspace = true
object.workspace = true
sha2.workspace = true
regex.workspace = true
serde_json.workspace = true
serialport.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
wiremock.workspace = true
