[package]
name = "firment-tools"
version.workspace = true
edition.workspace = true

[dependencies]
firment-core = { path = "../firment-core" }
async-trait.workspace = true
futures.workspace = true
globset.workspace = true
ignore.workspace = true
object.workspace = true
reqwest = { workspace = true, features = ["cookies"] }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serialport.workspace = true
sha2.workspace = true
tokio.workspace = true
toml.workspace = true
uuid = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
wiremock.workspace = true
object = { workspace = true, features = ["write"] }
